/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor;

import java.awt.Color;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;

/**
 *
 * @author student
 */
public class MainWindow extends javax.swing.JFrame {

    private File soubor;
    private final Soubor txtSoubor = new Soubor();
    private String kodovani = "UTF-8";
    private String searchText = "";
    private String replText = "";
    private String findText = "";
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        this.setTitle("Editor");
        initComponents();
    }
    
    private String informaceOSouboru() {
        String info = "";
        info += "Název souboru: " + soubor.getName() + "\n";
        info += "Umístění: " + soubor.getParent() + "\n";
        info += "Velikost: " + String.valueOf(soubor.length()) + " bytes\n";
        info += "Práva: ";
        info += soubor.canRead() ? "R " : "- ";
        info += soubor.canWrite() ? "W " : "- ";
        info += soubor.canExecute() ? "X\n" : "-\n";
        info += "Skrytý soubor: " + (soubor.isHidden() ? "ano " : "ne\n");
        Date datum = new Date();
        datum.setTime(soubor.lastModified());
        info += "Datum aktualizace: " + datum.toString();
        return info;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeGroup = new javax.swing.ButtonGroup();
        toolBar = new javax.swing.JToolBar();
        NewFileButton = new javax.swing.JButton();
        OpenFileButton = new javax.swing.JButton();
        SaveFileButton = new javax.swing.JButton();
        statusBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        editor = new javax.swing.JEditorPane();
        menuBar = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        NewFileItem = new javax.swing.JMenuItem();
        OpenFileItem = new javax.swing.JMenuItem();
        SaveFileItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        InfoFileItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        EndFile = new javax.swing.JMenuItem();
        MenuEdit = new javax.swing.JMenu();
        CutFileItem = new javax.swing.JMenuItem();
        CopyFileItem = new javax.swing.JMenuItem();
        PasteFileItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        FindFileItem = new javax.swing.JMenuItem();
        ReplaceFileItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        FindAllFileItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        loremusIpsumus = new javax.swing.JMenuItem();
        MenuSettings = new javax.swing.JMenu();
        ViewMenu = new javax.swing.JMenu();
        ToolsItem = new javax.swing.JCheckBoxMenuItem();
        StatusBarItem = new javax.swing.JCheckBoxMenuItem();
        BackgroundColorItem = new javax.swing.JMenuItem();
        FontItem = new javax.swing.JMenuItem();
        MenuCode = new javax.swing.JMenu();
        utf8Code = new javax.swing.JRadioButtonMenuItem();
        windowsCode = new javax.swing.JRadioButtonMenuItem();
        isoCode = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBar.setRollover(true);

        NewFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/new.png"))); // NOI18N
        NewFileButton.setText("Nový");
        NewFileButton.setFocusable(false);
        NewFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NewFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        NewFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFileButtonActionPerformed(evt);
            }
        });
        toolBar.add(NewFileButton);

        OpenFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/open.png"))); // NOI18N
        OpenFileButton.setText("Otevřít");
        OpenFileButton.setFocusable(false);
        OpenFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OpenFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        OpenFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileButtonActionPerformed(evt);
            }
        });
        toolBar.add(OpenFileButton);

        SaveFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/save.png"))); // NOI18N
        SaveFileButton.setText("Uložit");
        SaveFileButton.setFocusable(false);
        SaveFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileButtonActionPerformed(evt);
            }
        });
        toolBar.add(SaveFileButton);

        statusBar.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Název souboru");
        jLabel2.setOpaque(true);
        statusBar.add(jLabel2);

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vlastnosti souboru");
        jLabel3.setOpaque(true);
        statusBar.add(jLabel3);

        jLabel1.setBackground(new java.awt.Color(51, 102, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parametry textu");
        jLabel1.setOpaque(true);
        statusBar.add(jLabel1);

        jScrollPane2.setViewportView(editor);

        MenuFile.setText("Soubor");

        NewFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewFileItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/new-small.png"))); // NOI18N
        NewFileItem.setText("Nový");
        NewFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewFileItemActionPerformed(evt);
            }
        });
        MenuFile.add(NewFileItem);

        OpenFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenFileItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/open-small.png"))); // NOI18N
        OpenFileItem.setText("Otevřít...");
        OpenFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileItemActionPerformed(evt);
            }
        });
        MenuFile.add(OpenFileItem);

        SaveFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveFileItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikony/save-small.png"))); // NOI18N
        SaveFileItem.setText("Uložit...");
        MenuFile.add(SaveFileItem);
        MenuFile.add(jSeparator1);

        InfoFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        InfoFileItem.setText("Informace o souboru");
        InfoFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoFileItemActionPerformed(evt);
            }
        });
        MenuFile.add(InfoFileItem);
        MenuFile.add(jSeparator2);

        EndFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        EndFile.setText("Konec");
        EndFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndFileActionPerformed(evt);
            }
        });
        MenuFile.add(EndFile);

        menuBar.add(MenuFile);

        MenuEdit.setText("Úpravy");

        CutFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        CutFileItem.setText("Vyjmout");
        CutFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CutFileItemActionPerformed(evt);
            }
        });
        MenuEdit.add(CutFileItem);

        CopyFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        CopyFileItem.setText("Kopírovat");
        CopyFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyFileItemActionPerformed(evt);
            }
        });
        MenuEdit.add(CopyFileItem);

        PasteFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        PasteFileItem.setText("Vložit");
        MenuEdit.add(PasteFileItem);
        MenuEdit.add(jSeparator3);

        FindFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        FindFileItem.setText("Hledat..");
        FindFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindFileItemActionPerformed(evt);
            }
        });
        MenuEdit.add(FindFileItem);

        ReplaceFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        ReplaceFileItem.setText("Nahradit..");
        ReplaceFileItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReplaceFileItemActionPerformed(evt);
            }
        });
        MenuEdit.add(ReplaceFileItem);
        MenuEdit.add(jSeparator4);

        FindAllFileItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        FindAllFileItem.setText("Vybrat vše");
        MenuEdit.add(FindAllFileItem);
        MenuEdit.add(jSeparator5);

        loremusIpsumus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        loremusIpsumus.setText("Lorem ipsum");
        loremusIpsumus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loremusIpsumusActionPerformed(evt);
            }
        });
        MenuEdit.add(loremusIpsumus);

        menuBar.add(MenuEdit);

        MenuSettings.setText("Nastavení");

        ViewMenu.setText("Zobrazení");

        ToolsItem.setSelected(true);
        ToolsItem.setText("Panel Nástrojů");
        ToolsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToolsItemActionPerformed(evt);
            }
        });
        ViewMenu.add(ToolsItem);

        StatusBarItem.setSelected(true);
        StatusBarItem.setText("Stavový řádek");
        StatusBarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusBarItemActionPerformed(evt);
            }
        });
        ViewMenu.add(StatusBarItem);

        MenuSettings.add(ViewMenu);

        BackgroundColorItem.setText("Barva pozadí..");
        BackgroundColorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackgroundColorItemActionPerformed(evt);
            }
        });
        MenuSettings.add(BackgroundColorItem);

        FontItem.setText("Písmo..");
        FontItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FontItemActionPerformed(evt);
            }
        });
        MenuSettings.add(FontItem);

        MenuCode.setText("Kodovaní znaků..");
        MenuCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCodeActionPerformed(evt);
            }
        });

        codeGroup.add(utf8Code);
        utf8Code.setSelected(true);
        utf8Code.setText("UTF-8");
        utf8Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utf8CodeActionPerformed(evt);
            }
        });
        MenuCode.add(utf8Code);

        codeGroup.add(windowsCode);
        windowsCode.setText("Windows 1250");
        windowsCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowsCodeActionPerformed(evt);
            }
        });
        MenuCode.add(windowsCode);

        codeGroup.add(isoCode);
        isoCode.setText("ISO-8859-2");
        isoCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isoCodeActionPerformed(evt);
            }
        });
        MenuCode.add(isoCode);

        MenuSettings.add(MenuCode);

        menuBar.add(MenuSettings);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 463, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileButtonActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.setDialogType(JFileChooser.OPEN_DIALOG);
            fc.setDialogTitle("Otevření souboru");
            fc.setCurrentDirectory(new java.io.File("."));
            FileNameExtensionFilter myFilter = new FileNameExtensionFilter("Text", "txt");
            fc.setFileFilter(myFilter);
            if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
                soubor = fc.getSelectedFile();
                try {
                    txtSoubor.nactiZeSouboru(soubor, kodovani);
                    editor.setText(txtSoubor.getData());
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Požadovaný soubor nebyl nalezen.", "Chyba!", JOptionPane.ERROR_MESSAGE);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nastala chyba při otevření souboru!", "Chyba!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_OpenFileButtonActionPerformed

    private void OpenFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileItemActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.setDialogType(JFileChooser.OPEN_DIALOG);
            fc.setDialogTitle("Otevření souboru");
            fc.setCurrentDirectory(new java.io.File("."));
            FileNameExtensionFilter myFilter = new FileNameExtensionFilter("Text", "txt");
            fc.setFileFilter(myFilter);
            if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
                soubor = fc.getSelectedFile();
                try {
                    txtSoubor.nactiZeSouboru(soubor, kodovani);
                    editor.setText(txtSoubor.getData());
                } catch (FileNotFoundException ex) {
                    JOptionPane.showMessageDialog(this, "Požadovaný soubor nebyl nalezen.", "Chyba!", JOptionPane.ERROR_MESSAGE);
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nastala chyba při otevření souboru!", "Chyba!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_OpenFileItemActionPerformed

    private void searchOperation(String foundTxt, String replacedTxt,Boolean replace){
        editor.requestFocusInWindow();
        int startFrom=(editor.getCaretPosition() == editor.getDocument().getLength())? 0 : editor.getCaretPosition();
        int max = editor.getDocument().getLength() - startFrom;
        int searchIndex = -1;
        try{
            searchIndex = editor.getDocument().getText(startFrom, max).indexOf(foundTxt);
        }catch(BadLocationException ex){
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null,ex);
        }
        if(searchIndex != -1){
            editor.select(searchIndex+startFrom, searchIndex+startFrom+foundTxt.length());
            if(replace){
                editor.replaceSelection(replacedTxt);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Řetězec nebyl nalezen");
            editor.setSelectionStart(-1);
            editor.setSelectionEnd(-1);
        }
        
    }
    
    private void CopyFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyFileItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CopyFileItemActionPerformed

    private void ReplaceFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReplaceFileItemActionPerformed
        ReplaceDialog nahraditDialog= new ReplaceDialog(this,true,searchText,replText);
        
        if(nahraditDialog.showDialog().equals("Nahradit")){
            searchText = nahraditDialog.getReplacedText();
            replText = nahraditDialog.getNewText();
            this.searchOperation(searchText,replText,true);
        }
    }//GEN-LAST:event_ReplaceFileItemActionPerformed

    private void CutFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CutFileItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CutFileItemActionPerformed

    private void ToolsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToolsItemActionPerformed
        if (ToolsItem.isSelected()){
            toolBar.setVisible(true);
        } else {
            toolBar.setVisible(false);
        }
    }//GEN-LAST:event_ToolsItemActionPerformed

    private void StatusBarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusBarItemActionPerformed
        if (StatusBarItem.isSelected()){
            statusBar.setVisible(true);
        } else {
            statusBar.setVisible(false);
        }
    }//GEN-LAST:event_StatusBarItemActionPerformed

    private void BackgroundColorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackgroundColorItemActionPerformed
        Color barva = JColorChooser.showDialog(this, "Vyber si barvu", editor.getBackground());
        editor.setBackground(barva);
    }//GEN-LAST:event_BackgroundColorItemActionPerformed

    private void FontItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FontItemActionPerformed
        FontDialog upravaPisma=new FontDialog(this,true,editor.getFont(),editor.getForeground());
        if(upravaPisma.showDialog().equalsIgnoreCase("ok")){
            editor.setFont(upravaPisma.getTextFont());
            editor.setForeground(upravaPisma.getColor());
        }
    }//GEN-LAST:event_FontItemActionPerformed

    private void NewFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFileItemActionPerformed
        
    }//GEN-LAST:event_NewFileItemActionPerformed

    private void NewFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewFileButtonActionPerformed
       
    }//GEN-LAST:event_NewFileButtonActionPerformed

    private void SaveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileButtonActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.setDialogType(JFileChooser.SAVE_DIALOG);
            fc.setDialogTitle("Uložení souboru");
            fc.setCurrentDirectory(new java.io.File("."));
            FileNameExtensionFilter myFilter = new FileNameExtensionFilter("Text", "txt");
            fc.setFileFilter(myFilter);
            if (fc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
                    txtSoubor.setData(editor.getText());
                    txtSoubor.ulozDoSouboru(fc.getSelectedFile(), kodovani);
            }
        } catch (HeadlessException | FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Nastala chyba při otevření souboru!", "Chyba!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SaveFileButtonActionPerformed

    private void InfoFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoFileItemActionPerformed
        try {
            JOptionPane.showMessageDialog(this, this.informaceOSouboru(), "Informace o souboru", JOptionPane.INFORMATION_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Neexistující soubor!", "Chyba!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_InfoFileItemActionPerformed

    private void EndFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndFileActionPerformed
        this.dispose();
    }//GEN-LAST:event_EndFileActionPerformed

    private void FindFileItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindFileItemActionPerformed
        findText=JOptionPane.showInputDialog("Hledaný text",findText);
        this.searchOperation(findText, "", false);
    }//GEN-LAST:event_FindFileItemActionPerformed

    private void loremusIpsumusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loremusIpsumusActionPerformed
        this.editor.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque luctus aliquet dolor vitae ultricies. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sed sollicitudin est. Etiam rutrum metus diam, sed vestibulum velit efficitur eget. Duis aliquet tempus massa sit amet laoreet. Maecenas non eleifend justo, a placerat mauris. Proin sagittis ac libero eget venenatis. Pellentesque vel libero a tellus dignissim ultrices.");
    }//GEN-LAST:event_loremusIpsumusActionPerformed

    private void utf8CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utf8CodeActionPerformed
        this.kodovani="UTF-8";
    }//GEN-LAST:event_utf8CodeActionPerformed

    private void MenuCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCodeActionPerformed

    }//GEN-LAST:event_MenuCodeActionPerformed

    private void windowsCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsCodeActionPerformed
        this.kodovani="Windows 1250";
    }//GEN-LAST:event_windowsCodeActionPerformed

    private void isoCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isoCodeActionPerformed
        this.kodovani="ISO-8859-2";
    }//GEN-LAST:event_isoCodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BackgroundColorItem;
    private javax.swing.JMenuItem CopyFileItem;
    private javax.swing.JMenuItem CutFileItem;
    private javax.swing.JMenuItem EndFile;
    private javax.swing.JMenuItem FindAllFileItem;
    private javax.swing.JMenuItem FindFileItem;
    private javax.swing.JMenuItem FontItem;
    private javax.swing.JMenuItem InfoFileItem;
    private javax.swing.JMenu MenuCode;
    private javax.swing.JMenu MenuEdit;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenu MenuSettings;
    private javax.swing.JButton NewFileButton;
    private javax.swing.JMenuItem NewFileItem;
    private javax.swing.JButton OpenFileButton;
    private javax.swing.JMenuItem OpenFileItem;
    private javax.swing.JMenuItem PasteFileItem;
    private javax.swing.JMenuItem ReplaceFileItem;
    private javax.swing.JButton SaveFileButton;
    private javax.swing.JMenuItem SaveFileItem;
    private javax.swing.JCheckBoxMenuItem StatusBarItem;
    private javax.swing.JCheckBoxMenuItem ToolsItem;
    private javax.swing.JMenu ViewMenu;
    private javax.swing.ButtonGroup codeGroup;
    private javax.swing.JEditorPane editor;
    private javax.swing.JRadioButtonMenuItem isoCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem loremusIpsumus;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel statusBar;
    private javax.swing.JToolBar toolBar;
    private javax.swing.JRadioButtonMenuItem utf8Code;
    private javax.swing.JRadioButtonMenuItem windowsCode;
    // End of variables declaration//GEN-END:variables
}
