/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classeditor;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author student
 */
public class MainMenu extends javax.swing.JFrame {

    private int titleClicked;
    private boolean secret=false;
    public MainMenu() {
        initComponents();
        secretText.setVisible(false);
        this.setTitle("Role Play Game Adventure");
    }
    
    public void saveCharacter(Character character) {
        File f = new File("save.csv");
        int i=0;
        int id = 0;
        boolean same=false;
        if (f.exists() && !f.isDirectory()) {
            try (BufferedReader br = new BufferedReader(new FileReader("save.csv"))) {
                String s;
                do{
                    id=(int)Math.floor(Math.random()*1000);
                    while ((s = br.readLine()) != null) {
                        if(i!=0){
                            String[] attr = s.split(";");
                            if(id == Integer.parseInt(attr[0])){
                                same=true;
                            }
                        }
                        i++;
                    }        
                }while(same);
            } catch (Exception e) {
                System.err.println("Chyba při četení ze souboru.");
            }
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("save.csv", true))) {
                bw.newLine();
                String output=id+";"+character.getClass().getSimpleName()+";"+character.getFirstname()+";"+character.getSurname()+";"+character.getFather()+";"+character.getSex();
                bw.write(output);
                bw.flush();
            } catch (Exception e) {
                System.err.println("Do souboru se nepovedlo zapsat.");
            }
        }
        else{
            id=(int)Math.floor(Math.random()*1000);
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("save.csv"))) {
                bw.write("id;class;firstname;surname;father;sex");
                bw.newLine();
                String output=id+";"+character.getClass().getSimpleName()+";"+character.getFirstname()+";"+character.getSurname()+";"+character.getFather()+";"+character.getSex();
                bw.write(output);
                bw.flush();
            } catch (Exception e) {
                System.err.println("Do souboru se nepovedlo zapsat.");
            }
        }
    }
    
    public void deleteSaveFile(){
        try {
            File file = new File("save.csv");
            if (file.delete()) {
                System.out.println(file.getName() + " is deleted!");
            } else {
                System.out.println("Delete operation is failed.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void back(JFrame frame){
        frame.dispose();
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JButton();
        newCharacterButton = new javax.swing.JButton();
        mainMenuTitle = new javax.swing.JLabel();
        characterListButton = new javax.swing.JButton();
        secretText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        newCharacterButton.setText("New character");
        newCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCharacterButtonActionPerformed(evt);
            }
        });

        mainMenuTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainMenuTitle.setText("Role Play Game Adventure");
        mainMenuTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMenuTitleMouseClicked(evt);
            }
        });

        characterListButton.setText("Character list");
        characterListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                characterListButtonActionPerformed(evt);
            }
        });

        secretText.setForeground(new java.awt.Color(255, 51, 51));
        secretText.setText("Secret unlocked");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newCharacterButton)
                            .addComponent(characterListButton)
                            .addComponent(mainMenuTitle))
                        .addGap(0, 87, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(secretText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secretText)
                .addGap(26, 26, 26)
                .addComponent(newCharacterButton)
                .addGap(26, 26, 26)
                .addComponent(characterListButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void newCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCharacterButtonActionPerformed
        NewCharacter newChar = new NewCharacter(this,true,secret);
        this.setVisible(false);
        if(newChar.showDialog().equalsIgnoreCase("Ok")){
            this.setVisible(true);
            saveCharacter(newChar.getCharacter());
        }
        else{
            this.setVisible(true);
        }
        
    }//GEN-LAST:event_newCharacterButtonActionPerformed

    private void characterListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_characterListButtonActionPerformed
        LoadCharacters loadCharacters=new LoadCharacters(this);
        this.setVisible(false);
    }//GEN-LAST:event_characterListButtonActionPerformed

    private void mainMenuTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMenuTitleMouseClicked
        titleClicked++;
        if (titleClicked == 10) {
            mainMenuTitle.setForeground(Color.red);
            secretText.setVisible(true);
            this.secret=true;
            Timer timer = new Timer(3000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent arg0) {
                    secretText.setVisible(false);
                    mainMenuTitle.setForeground(Color.BLACK);
                }
            });
            timer.setRepeats(false);
            timer.start();
        }
    }//GEN-LAST:event_mainMenuTitleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton characterListButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel mainMenuTitle;
    private javax.swing.JButton newCharacterButton;
    private javax.swing.JLabel secretText;
    // End of variables declaration//GEN-END:variables
}
